Repository openshift/cloud-provider-openstack, pull requests merged in 2023-01, with the labels that each got.

#161 Bug OCPBUGS-1646: Make sure LB status is updated immediately
  pkg/openstack/loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#158 OCPBUGS-5012: Sync with upstream release-1.23
  Makefile
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  cluster/images/barbican-kms-plugin/Dockerfile
  cluster/images/barbican-kms-plugin/Dockerfile.build
  cluster/images/k8s-keystone-auth/Dockerfile
  cluster/images/k8s-keystone-auth/Dockerfile.build
  cluster/images/magnum-auto-healer/Dockerfile
  cluster/images/magnum-auto-healer/Dockerfile.build
  cluster/images/manila-csi-plugin/Dockerfile
  cluster/images/manila-csi-plugin/Dockerfile.build
  cluster/images/octavia-ingress-controller/Dockerfile
  cluster/images/octavia-ingress-controller/Dockerfile.build
  cluster/images/openstack-cloud-controller-manager/Dockerfile
  cluster/images/openstack-cloud-controller-manager/Dockerfile.build
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/cloudprovider/register/register.go
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/manila/validator/validator.go
  pkg/ingress/controller/controller.go
  pkg/kms/barbican/barbican.go
  pkg/openstack/instances.go
  pkg/openstack/instances_test.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
  pkg/util/errors/errors.go
  pkg/util/mount/mount.go
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
  tests/playbooks/roles/install-k3s/defaults/main.yaml
  tests/playbooks/roles/install-k3s/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
  tests/playbooks/test-csi-manila-e2e.yaml
  tests/playbooks/test-occm-e2e.yaml
  tests/sanity/cinder/fakemount.go
Labels: lgtm, do-not-merge/hold, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#164 [release-4.12] Bug OCPBUGS-5403: Make sure LB status is updated immediately
  pkg/openstack/loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#172 OCPBUGS-6064: Merge https://github.com/kubernetes/cloud-provider-openstack:release-1.25 into release-4.12
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  pkg/openstack/instances.go
  pkg/openstack/instances_test.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
