Repository openshift/cloud-provider-openstack, pull requests merged in 2023-10, with the labels that each got.

#220 OCPBUGS-20124: FastFix: Merge https://github.com/kubernetes/cloud-provider-openstack:release-1.25 into release-4.12
  README.md
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/playbooks/roles/install-docker/defaults/main.yml
  tests/playbooks/roles/install-docker/tasks/main.yml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#223 CARRY: Add DOWNSTREAM_OWNERS
  DOWNSTREAM_OWNERS
  DOWNSTREAM_OWNERS_ALIASES
Labels: lgtm, approved

#226 OCPBUGS-21614: Merge branch 'release-1.27' into release-4.14
  pkg/openstack/loadbalancer.go
  pkg/util/util.go
  tests/ci-csi-cinder-e2e.sh
  tests/ci-csi-manila-e2e.sh
  tests/ci-occm-e2e.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
